# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'RxAlamofire'

  pod 'DateTools'

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod 'ObjectMapper', '~> 2.2'

  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'

  pod 'SwiftyJSON'
end
